name: Vinted scraping + conditional email

on:
  schedule:
    - cron: "0 8-22/2 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download SQLite DB artifact
        uses: actions/download-artifact@v4
        with:
          name: vinted-db
          path: data/output
        continue-on-error: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug memory
        run: free -h

      - name: Scrape
        env:
          ENV: "ci"
        run: python src/main.py

      - name: Send email if needed
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PWD: ${{ secrets.EMAIL_PWD }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          ENV: "ci"
        run: python src/send_email.py

      - name: Upload SQLite DB artifact
        uses: actions/upload-artifact@v4
        with:
          name: vinted-db
          path: data/output/vinted.db